(add-to-list 'load-path "~/.emacs.d/vendor")
(require 'quack)
(defun open-snippet-directory (arg)
  (interactive "sOpen snippets directory (enter)")
  (find-file "~/.emacs.d/vendor/yasnippet/snippets/"))
(defun open-vendor-directory (arg)
  (interactive "sOpen vendor directory (enter)")
  (find-file "~/.emacs.d/vendor/"))
(provide 'jong-lisp)
